chore: add jira ticket link to pull_request_template.md
wealthsimple/.github pull request #8
Opened 2024-07-03 18:08 UTC by JackieSL1

### Jira Ticket
https://wealthsimple.atlassian.net/browse/BEPLAT-1021

### Why
For compliance reasons, every PR should be linked to a Jira ticket. To encourage this behaviour, this PR adds a section to the pull request template to include a ticket.

### What is changing
* Added a Jira ticket section to `pull_request_template.md`

### Next steps
To further enforce Jira ticket inclusion in PRs, a GitHub workflow should be created in the future to issue a warning when a PR is created without a ticket link.

2024-07-03 18:19 UTC, scottybarr requested changes
Thanks! Made a small suggestion!

2024-07-03 18:19 UTC, scottybarr commented on .github/pull_request_template.md
> +<!-- If your PR addresses a Jira ticket, link it here -->
```suggestion
<!-- Please include a link to an associated JIRA ticket. Hotfixes / Incidents do not require JIRA tickets, but most changes should be scoped and tracked. -->
```

2024-07-04 12:51 UTC, JackieSL1 commented
> Thanks! Made a small suggestion!

Updated, @scottybarr !

2024-07-04 13:05 UTC, scottybarr approved these changes

2024-07-04 14:38 UTC, merged